### ISSUE TITLE
How can I run it in development mode?

### ISSUE THREAD

**Issue by al3rez** [zachahn/disqualified#3]
Currently I cannot run the worker on development mode but only on production mode, is there a reason for it?

**Comment by zachahn** [comment]
I run it in development mode! What issue are you running into?

**Comment by al3rez** [comment]
It shows nothing, no ascii or any logging, and I run rails gem "rails", "~> 7.1.3", ">= 7.1.3.4" and ruby 3.3.1

**Comment by al3rez** [comment]
> It shows nothing, no ascii or any logging, and I run rails gem "rails", "~> 7.1.3", ">= 7.1.3.4" and ruby 3.3.1

kind of stucks

**Comment by zachahn** [comment]
Did you customize your Rails logger level? The app prints out the ascii art using `Rails.logger.info` by default, so I think lowering your log level might help. You can override the logger that the Disqualified server uses

```ruby
# config/initializers/disqualified.rb
Disqualified.configure_server do |config|
  config.logger = Logger.new
end
```

**Comment by al3rez** [comment]
made it work!
